"""empty message

Revision ID: 0e710a0b592e
Revises: 46c2188aea05
Create Date: 2024-07-25 01:15:52.277313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e710a0b592e'
down_revision = '46c2188aea05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('phone_sell_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['phone_sell_id'], ['phones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    # ### end Alembic commands ###
