"""empty message

Revision ID: 38b56d397b25
Revises: 65c16e6cb7c8
Create Date: 2024-06-23 09:57:33.088452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b56d397b25'
down_revision = '65c16e6cb7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
