"""empty message

Revision ID: 46c2188aea05
Revises: 95b3e09a726a
Create Date: 2024-07-24 01:02:16.368350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c2188aea05'
down_revision = '95b3e09a726a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('phone_sell_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['phone_sell_id'], ['phones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###
