"""empty message

Revision ID: 6c4a4619fb1c
Revises: cf7c1d58e1f5
Create Date: 2024-06-17 01:21:05.672631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4a4619fb1c'
down_revision = 'cf7c1d58e1f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='address_pkey'),
    sa.UniqueConstraint('address', name='address_address_key')
    )
    # ### end Alembic commands ###
