"""empty message

Revision ID: 742e464c5367
Revises: 0f246f780dba
Create Date: 2024-07-21 18:02:32.219385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742e464c5367'
down_revision = '0f246f780dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('phone_sell_id', sa.Integer(), nullable=True),
    sa.Column('payment_amount', sa.Integer(), nullable=True),
    sa.Column('payout_amount', sa.Integer(), nullable=True),
    sa.Column('shipping_address', sa.String(length=2000), nullable=True),
    sa.Column('payment_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('payout_transaction_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['phone_sell_id'], ['phones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    # ### end Alembic commands ###
