"""empty message

Revision ID: 863594b16839
Revises: 
Create Date: 2024-06-21 23:51:38.274820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863594b16839'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('storage', sa.String(length=50), nullable=True),
    sa.Column('carrier', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('seller', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('shipping', sa.String(length=50), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('user_email', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phones')
    op.drop_table('user')
    # ### end Alembic commands ###
