"""empty message

Revision ID: 86616f42fa3c
Revises: aba8da285da5
Create Date: 2024-06-22 01:26:25.625348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86616f42fa3c'
down_revision = 'aba8da285da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.drop_column('shipping')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
