"""empty message

Revision ID: aae3142b3529
Revises: 0e710a0b592e
Create Date: 2024-08-03 09:46:15.413151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae3142b3529'
down_revision = '0e710a0b592e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint('cart_phone_sell_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'phones', ['phone_sell_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_phone_sell_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'phones', ['phone_sell_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_phone_sell_id_fkey', 'phones', ['phone_sell_id'], ['id'])

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_phone_sell_id_fkey', 'phones', ['phone_sell_id'], ['id'])

    # ### end Alembic commands ###
