"""empty message

Revision ID: b9540bdfe763
Revises: 433b40d76353
Create Date: 2024-09-08 02:09:43.139928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9540bdfe763'
down_revision = '433b40d76353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribed', schema=None) as batch_op:
        batch_op.drop_column('meeting_id')

    # ### end Alembic commands ###
