"""empty message

Revision ID: df9ade25be52
Revises: b9540bdfe763
Create Date: 2024-09-08 13:22:57.434576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9ade25be52'
down_revision = 'b9540bdfe763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_email', sa.String(length=120), nullable=True),
    sa.Column('participant_email', sa.String(length=120), nullable=True),
    sa.Column('meeting_link', sa.String(), nullable=True),
    sa.Column('passcode', sa.String(), nullable=True),
    sa.Column('meeting_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['participant_email'], ['user.email'], ),
    sa.ForeignKeyConstraint(['subscriber_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscribed', schema=None) as batch_op:
        batch_op.drop_column('passcode')
        batch_op.drop_column('meeting_link')
        batch_op.drop_column('meeting_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('meeting_link', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('passcode', sa.VARCHAR(), autoincrement=False, nullable=True))

    op.drop_table('meetings')
    # ### end Alembic commands ###
